name: phidget-hello-world-python
version: '0.1'
summary: Phidget HelloWorld python example.
description: |
  Test snap installs with the Phidget HelloWorld python example.

grade: devel
confinement: devmode

apps:
  phidget-hello-world-python:
    command: bin/phidget-hello-world

parts:
  phidget-python:
    plugin: python
    python-version: python3
    source: https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
  phidget-hello-world-python:
    plugin: python
    python-version: python3
    source: .
    after: [phidget-python]
