name: phidget-hello-world-python
version: '0.1'
summary: Phidget HelloWorld python example.
description: |
  Test snap installs with the Phidget HelloWorld python example.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  phidget-hello-world-python:
    command: phidget-hello-world-python

parts:
  phidget-python:
    plugin: python
    python-version: python3
    source: https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
  phidget-hello-world-python:
    plugin: python
    python-version: python3
    source: .
    after: [phidget-python]
