name: phidget-hello-world-python
version: '0.1'
summary: Phidget HelloWorld python example.
description: |
  Test snap installs with the Phidget HelloWorld python example.

grade: devel
confinement: devmode

apps:
  phidget-hello-world-python:
    command: bin/phidget-hello-world

parts:
  libphidget22:
    plugin: make
    source: https://www.phidgets.com/downloads/phidget22/libraries/linux/libphidget22.tar.gz
    override-build: |
     ./configure
     make
     sudo make install
  phidget22-python:
    plugin: python
    python-version: python3
    source: https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
    after: [libphidget22]
  phidget-hello-world-python:
    plugin: python
    python-version: python3
    source: .
    after: [phidget22-python]
