name: phidget-hello-world-python
version: '0.1'
summary: Phidget HelloWorld python example.
description: |
  Test snap installs with the Phidget HelloWorld python example.

grade: devel
confinement: devmode

apps:
  phidget-hello-world-python:
    command: bin/phidget-hello-world

parts:
  libphidget22:
    plugin: make
    source: https://www.phidgets.com/downloads/phidget22/libraries/linux/libphidget22.tar.gz
    build-packages:
      - build-essential
    stage-packages:
      - libusb-1.0-0-dev
    override-build: |
      ./configure --prefix=/usr
      make
      sudo make install
    stage:
      - $binaries
    prime:
      - $binaries
  phidget22-python:
    plugin: python
    python-version: python3
    source: https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
    after: [libphidget22]
  phidget-hello-world-python:
    plugin: python
    python-version: python3
    source: .
    after: [phidget22-python]
