name: phidget-hello-world-python
version: '0.1'
summary: Phidget HelloWorld python example.
description: |
  Phidget HelloWorld python example.

grade: devel
confinement: strict

apps:
  phidget-hello-world-python:
    command: bin/phidget-hello-world
    plugs: [raw-usb]

parts:
  libusb:
    plugin: nil
    stage-packages:
      - libusb-1.0-0-dev
  libphidget22:
    plugin: make
    source: https://www.phidgets.com/downloads/phidget22/libraries/linux/libphidget22.tar.gz
    override-pull: |
      snapcraftctl pull
      ./configure --prefix=/usr
    filesets:
      libraries:
        - usr/lib/libphidget*
    prime:
      - $libraries
    after: [libusb]
  phidget22-python:
    plugin: python
    python-version: python3
    source: https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
    override-build: |
      cd Phidget22Python
      snapcraftctl build
      pip3 install .
    filesets:
      libraries:
        - usr/*
    prime:
      - $libraries
  phidget-hello-world-python:
    plugin: python
    python-version: python3
    source: .
